import { chromium } from 'playwright';
const dir='/tmp/claude-0/-home-user-New/c47b453a-ac8c-5a8c-8086-dfced9a9bf53/scratchpad/';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport:{width:1440,height:900} });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://localhost:3000',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
await p.screenshot({path:dir+'dbg.png'});
console.log('buttons:', await p.$$eval('button', bs=>bs.map(x=>x.innerText.trim().split('\n')[0]).slice(0,10)));
console.log('errors:', errs.slice(0,3));
await b.close();
