/* html.mjs — dependency-free extraction of the handful of HTML features the
   SEO rules care about.

   This is deliberately not a parser. The pages it reads are generated by
   scripts/build-articles.mjs or hand-written to the same shell, so the markup
   is well-formed and predictable. What we need is title/meta/heading/link/
   image/JSON-LD extraction that is accurate on *that* markup, and every
   helper here strips comments and script/style bodies first so commented-out
   tags never register as real ones.
*/

const VOID_SAFE = /<!--[\s\S]*?-->/g;

/** Drop HTML comments. Run before any tag matching. */
export const stripComments = (html) => html.replace(VOID_SAFE, '');

/** Drop <script> and <style> bodies, keeping the surrounding markup. */
export const stripScripts = (html) => html
  .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '')
  .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '');

const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  mdash: '—', ndash: '–', hellip: '…', rsquo: '’',
  lsquo: '‘', ldquo: '“', rdquo: '”', times: '×',
};

/* Search engines count the rendered character, not the entity that encodes it:
   "&amp;" is one character in a SERP, five in the source. Every length check
   in the rules runs on decoded text for that reason. */
export function decode(s) {
  return String(s)
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&([a-z]+);/gi, (m, name) => ENTITIES[name.toLowerCase()] ?? m);
}

/** Collapse whitespace and decode entities — the form a crawler would display. */
export const norm = (s) => decode(String(s)).replace(/\s+/g, ' ').trim();

/** Parse an attribute list into a lowercase-keyed object. */
export function attrs(tag) {
  const out = {};
  const re = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g;
  // Skip the tag name itself.
  const inner = tag.replace(/^<\s*[a-zA-Z0-9-]+/, '').replace(/\/?>$/, '');
  let m;
  while ((m = re.exec(inner))) out[m[1].toLowerCase()] = m[2] ?? m[3] ?? m[4] ?? '';
  return out;
}

/** All tags of a given name, as raw strings. */
export function tags(html, name) {
  const re = new RegExp(`<${name}\\b[^>]*>`, 'gi');
  return html.match(re) || [];
}

export function headHtml(html) {
  const m = /<head\b[^>]*>([\s\S]*?)<\/head>/i.exec(html);
  return m ? m[1] : '';
}

export function bodyHtml(html) {
  const m = /<body\b[^>]*>([\s\S]*?)<\/body>/i.exec(html);
  return m ? m[1] : html;
}

export function title(html) {
  const m = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(stripComments(html));
  return m ? norm(m[1]) : null;
}

export function htmlLang(html) {
  const m = /<html\b[^>]*>/i.exec(html);
  return m ? (attrs(m[0]).lang ?? null) : null;
}

/** <meta name="..."> content, decoded. */
export function metaName(html, name) {
  const clean = stripComments(html);
  for (const tag of tags(clean, 'meta')) {
    const a = attrs(tag);
    if ((a.name || '').toLowerCase() === name.toLowerCase()) return norm(a.content ?? '');
  }
  return null;
}

/** <meta property="..."> content (Open Graph), decoded. */
export function metaProperty(html, prop) {
  const clean = stripComments(html);
  for (const tag of tags(clean, 'meta')) {
    const a = attrs(tag);
    if ((a.property || '').toLowerCase() === prop.toLowerCase()) return norm(a.content ?? '');
  }
  return null;
}

/** href of <link rel="canonical">. */
export function canonical(html) {
  const clean = stripComments(html);
  for (const tag of tags(clean, 'link')) {
    const a = attrs(tag);
    if ((a.rel || '').toLowerCase().split(/\s+/).includes('canonical')) return (a.href || '').trim();
  }
  return null;
}

/** The robots directives that apply, lowercased — from meta robots + googlebot. */
export function robotsDirectives(html) {
  const out = new Set();
  for (const name of ['robots', 'googlebot']) {
    const v = metaName(html, name);
    if (v) v.split(',').forEach((d) => out.add(d.trim().toLowerCase()));
  }
  return out;
}

/** Headings in document order: [{ level, text }]. */
export function headings(html) {
  const src = stripScripts(stripComments(bodyHtml(html)));
  const out = [];
  const re = /<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi;
  let m;
  while ((m = re.exec(src))) {
    out.push({ level: Number(m[1]), text: norm(m[2].replace(/<[^>]*>/g, ' ')) });
  }
  return out;
}

/** Images in the body: [{ src, alt, hasAlt, width, height, loading }]. */
export function images(html) {
  const src = stripComments(bodyHtml(html));
  return tags(src, 'img').map((tag) => {
    const a = attrs(tag);
    return {
      src: a.src ?? '',
      alt: a.alt,
      hasAlt: Object.hasOwn(a, 'alt'),
      width: a.width,
      height: a.height,
      loading: a.loading,
      tag,
    };
  });
}

/** Anchors in the body: [{ href, text, rel, target }]. */
export function links(html) {
  const src = stripScripts(stripComments(bodyHtml(html)));
  const out = [];
  const re = /<a\b([^>]*)>([\s\S]*?)<\/a>/gi;
  let m;
  while ((m = re.exec(src))) {
    const a = attrs(`<a ${m[1]}>`);
    if (a.href === undefined) continue;
    out.push({
      href: a.href.trim(),
      text: norm(m[2].replace(/<[^>]*>/g, ' ')),
      rel: (a.rel || '').toLowerCase(),
      target: a.target || '',
      ariaLabel: a['aria-label'] || '',
    });
  }
  return out;
}

/** Parsed JSON-LD blocks: [{ ok, data | error, raw }]. */
export function jsonLd(html) {
  const out = [];
  const re = /<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(html))) {
    const raw = m[1].trim();
    try {
      out.push({ ok: true, data: JSON.parse(raw), raw });
    } catch (err) {
      out.push({ ok: false, error: err.message, raw });
    }
  }
  return out;
}

/** Flatten a JSON-LD block into the list of node objects it declares. */
export function ldNodes(data) {
  if (Array.isArray(data)) return data.flatMap(ldNodes);
  if (!data || typeof data !== 'object') return [];
  if (Array.isArray(data['@graph'])) return data['@graph'].flatMap(ldNodes);
  return [data];
}

/** Visible text of the body, for word counts. */
export function visibleText(html) {
  return norm(stripScripts(stripComments(bodyHtml(html))).replace(/<[^>]*>/g, ' '));
}

export const wordCount = (html) => {
  const t = visibleText(html);
  return t ? t.split(/\s+/).length : 0;
};
